name: ra3d
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2  # Tu versi√≥n actual

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.2.1
  go_router: ^17.0.1
  provider: ^6.1.5+1
  # Bajamos a 1.9.3 para que sea compatible con tu SDK 3.9.2
  model_viewer_plus: ^1.9.3
  shared_preferences: ^2.5.4
  # Mantener esta para evitar el error de "Registrar" en Flutter moderno
  permission_handler: ^11.3.1
  ar_flutter_plugin: ^0.7.3

dependency_overrides:
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true